package com.vnnovate.greendao.Entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEACHER".
*/
public class TeacherDao extends AbstractDao<Teacher, Long> {

    public static final String TABLENAME = "TEACHER";

    /**
     * Properties of entity Teacher.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Teacher_Id = new Property(0, Long.class, "Teacher_Id", true, "_id");
        public final static Property TeacherName = new Property(1, String.class, "TeacherName", false, "TEACHER_NAME");
        public final static Property Salary = new Property(2, int.class, "Salary", false, "SALARY");
        public final static Property City = new Property(3, String.class, "City", false, "CITY");
    }


    public TeacherDao(DaoConfig config) {
        super(config);
    }
    
    public TeacherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEACHER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Teacher_Id
                "\"TEACHER_NAME\" TEXT," + // 1: TeacherName
                "\"SALARY\" INTEGER NOT NULL ," + // 2: Salary
                "\"CITY\" TEXT);"); // 3: City
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEACHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Teacher entity) {
        stmt.clearBindings();
 
        Long Teacher_Id = entity.getTeacher_Id();
        if (Teacher_Id != null) {
            stmt.bindLong(1, Teacher_Id);
        }
 
        String TeacherName = entity.getTeacherName();
        if (TeacherName != null) {
            stmt.bindString(2, TeacherName);
        }
        stmt.bindLong(3, entity.getSalary());
 
        String City = entity.getCity();
        if (City != null) {
            stmt.bindString(4, City);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Teacher entity) {
        stmt.clearBindings();
 
        Long Teacher_Id = entity.getTeacher_Id();
        if (Teacher_Id != null) {
            stmt.bindLong(1, Teacher_Id);
        }
 
        String TeacherName = entity.getTeacherName();
        if (TeacherName != null) {
            stmt.bindString(2, TeacherName);
        }
        stmt.bindLong(3, entity.getSalary());
 
        String City = entity.getCity();
        if (City != null) {
            stmt.bindString(4, City);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Teacher readEntity(Cursor cursor, int offset) {
        Teacher entity = new Teacher( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Teacher_Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // TeacherName
            cursor.getInt(offset + 2), // Salary
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // City
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Teacher entity, int offset) {
        entity.setTeacher_Id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTeacherName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSalary(cursor.getInt(offset + 2));
        entity.setCity(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Teacher entity, long rowId) {
        entity.setTeacher_Id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Teacher entity) {
        if(entity != null) {
            return entity.getTeacher_Id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Teacher entity) {
        return entity.getTeacher_Id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
